version: '3'
networks:
  app-networks: null
services:
  nodejs:
    image: node:18
    container_name: 'node_CLIENT_HRM'
    working_dir: /var/www/html
    volumes:
      - './dist:/var/www/html'
    environment:
    networks:
      - app-networks
