version: '3'
networks:
  app-networks: null
services:
  nodejs:
    image: node:18
    container_name: 'node_CLIENT_HRM'
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
    environment:
      NODE_ENV: development
    command: npm install && npm run dev
    networks:
      - app-networks
