version: '3'
networks:
  app-networks: null
services:
  npm:
    image: node:18
    container_name: 'npm_CLIENT_HRM'
    volumes:
      - '.:/var/www/html'
    working_dir: /var/www/html
    entrypoint:
      - npm
