version: '3'
networks:
  app-networks: null
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: 'nginx_HRM_Client'
    ports:
      - '80:80'
    volumes:
      - './dist/hrm:/var/www/html'
      - './nginx-conf/nginx-default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - app-networks

  npm:
    image: node:18
    container_name: 'npm_HRM_Client'
    volumes:
      - '.:/var/www/html'
    working_dir: /var/www/html
    entrypoint:
      - npm
